import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import axios from 'axios';
import _ from 'lodash';
import { motion } from 'framer-motion';
import {
  Autocomplete,
  Box,
  Card,
  CardContent,
  Link,
  Stack,
  TextField,
  Typography
} from '@mui/material';
import LineChart from '../components/LineChart';


export default function Home() {
  const [query, setQuery] = useState("");
  const [queryRes, setQueryRes] = useState([]);
  const [landingStock, setLandingStock] = useState({});

  useEffect(() => {
    const landing = () => {
      axios.get("https://api.twelvedata.com/time_series?symbol=AAPL&interval=1min&apikey=demo&source=docs")
        .then((resp) => {
          setLandingStock(resp.data);
        })
        .catch((error) => {
          alert(error);
        });
    }
    landing();
  }, []);

  useEffect(() => {
    const searchDB = () => {
      axios.get(`https://api.twelvedata.com/stocks?symbol=${query}&source=docs`)
        .then(res => {
          setQueryRes(res.data);
        })
        .catch(error => alert(error));
    };
    searchDB();
  }, [query])


  const updateQuery = e => setQuery(e?.target?.value);
  const debounceOnChange = _.debounce(updateQuery, 500);
  console.log(queryRes)

  return (
    <Box className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box className={styles.main}>
          {
            !_.isEmpty(queryRes) &&
            // <Autocomplete
            //   id="search"
            //   getOptionLabel={() => `${queryRes.data.name}\n${queryRes.data.symbol} — $${queryRes.data.exchange}`}
            //   options={queryRes.data}
            //   sx={{ width: '33vw', padding: '1rem', }}
            //   noOptionsText={"There are no stock symbols that match your search"}
            //   renderOption={(props) => (
            //     <Box component='li' {...props} key={queryRes.exchange}>
            //       {queryRes.data.name} {queryRes.data.exchange}
            //     </Box>)}
            //   renderInput={(params) => <TextField {...params} placeholder='Search a symbol...' onChange={debounceOnChange} sx={{ fontWeight: 600 }}/>}
            // />
            <TextField
              id="search"
              placeholder='Search a symbol...'
              variant='outlined'
              onChange={debounceOnChange}
              sx={{ width: '33vw', padding: '1rem', fontWeight: 600 }}
            />
          }
          <motion.div
            animate={{
              y: [50, 0],
              opacity: [0, 1],
              animationDelay: 0.05
            }}
          >
            <Box className={styles.grid} sx={{ padding: '1rem' }}>
              <Card className={styles.card} elevation={0} sx={{ width: '33vw', height: '40vh', backgroundColor: '#fafafa' }}>
                <Link href='/AAPL' underline='none' color={'#1a1a1a'}>
                  <Stack direction='column'>
                    <Typography variant='body1' fontWeight={'700'} sx={{ width: '100%' }}>
                      Apple Inc
                    </Typography>
                    <Typography sx={{fontSize: '0.813rem'}}>
                      {
                        !_.isEmpty(landingStock) && `${landingStock.meta.symbol} — ${landingStock.meta.exchange}`
                      }
                    </Typography>
                  </Stack>
                </Link>
                <CardContent>
                  {
                    !_.isEmpty(landingStock) &&
                    <LineChart stock={landingStock} />
                  }
                </CardContent>
              </Card>
            </Box>
          </motion.div>
        </Box>
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          underline='none'
        >
          <Typography fontWeight={700} sx={{color: '#1a1a1a'}}>
            Powered by
          </Typography>
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Link>
      </footer>
    </Box>
  )
}
