import { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import axios from 'axios';
import _ from 'lodash';
import { motion } from 'framer-motion';
import {
  Box,
  Card,
  CardHeader,
  CardContent,
  Grid,
  Link,
  Stack,
  Typography
} from '@mui/material';
import LineChart from '../components/LineChart';
import Virtualize from '../components/Searchbar';


export default function Home() {
  const [landingStock, setLandingStock] = useState({});
  const [options, setOptions] = useState([]);

  useEffect(() => {
    const landing = () => {
      axios.get("https://api.twelvedata.com/time_series?symbol=AAPL&interval=1min&apikey=demo&source=docs")
        .then((resp) => {
          setLandingStock(resp.data);
        })
        .catch((error) => {
          alert(error);
        });
    }
    const searchDB = () => {
      axios
        .get(`https://api.twelvedata.com/stocks?source=docs`)
        .then((res) => {
          setOptions(res.data);
        })
        .catch((error) => alert(error));
    };
    landing();
    searchDB();
  }, []);

  return (
    <Box className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid container className={styles.main} direction='row'>
          {/* <Grid item>

          </Grid> */}
          <Grid item>
            <Box>
              <motion.div
                animate={{
                  y: [50, 0],
                  opacity: [0, 1],
                  animationDelay: 0.05
                }}
              >
                <Box className={styles.grid} sx={{ padding: '1rem' }}>
                  <Virtualize options={options} />
                  <Card className={styles.card} elevation={0} >
                    <CardContent>
                      
                    </CardContent>
                  </Card>
                  <Card className={styles.card} elevation={0} sx={{ width: '50vw', height: '60vh' }}>
                      <Stack direction='row' spacing={10}>
                        <Link href='/AAPL' underline='none' color={'#1a1a1a'}>
                          <Stack direction='column'>
                            <Typography variant='body1' fontWeight={'700'} sx={{ width: '100%' }}>
                              Apple Inc
                            </Typography>
                            <Typography sx={{ fontSize: '0.813rem' }}>
                              {
                                !_.isEmpty(landingStock) && `${landingStock.meta.symbol} — ${landingStock.meta.exchange}`
                              }
                            </Typography>
                          </Stack>
                        </Link>
                        
                      </Stack>
                    <CardContent>
                      {
                        !_.isEmpty(landingStock) &&
                        <LineChart stock={landingStock} />
                      }
                    </CardContent>
                  </Card>
                </Box>
              </motion.div>
            </Box>
          </Grid>
        </Grid>
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          underline='none'
        >
          <Typography fontWeight={700} sx={{ color: '#1a1a1a' }}>
            Powered by
          </Typography>
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </Link>
      </footer>
    </Box>
  )
}
